version: '3.7'
services:
  sonar-scanner:
    container_name: sonar-scanner
    platform: linux/amd64
    images: sonarsource/sonar-scanner-cli
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    command: sonar-scanner
    networks:
      - sonarqube-networks